### ISSUE TITLE
ValueError: nan in motion

### ISSUE THREAD

**Issue by guson98** [Dai-Wenxun/MotionLCM#13]
Hi,
When i try to run the training script  ```python -m train_motionlcm --cfg configs/motionlcm_t2m.yaml```, I get the following error:

```
07/24/2024 12:33:07 - INFO - __main__ - Training guidance scale range (w): [5.0, 15.0]
07/24/2024 12:33:07 - INFO - __main__ - EMA rate (mu): 0.95
07/24/2024 12:33:07 - INFO - __main__ - Skipping interval (k): 20.0
07/24/2024 12:33:07 - INFO - __main__ - Loss type (huber or l2): huber
Loading HumanML3D train ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:03
Loading HumanML3D test ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
07/24/2024 12:33:10 - INFO - __main__ - Loading pretrained model: experiments_t2m/mld_humanml/mld_humanml.ckpt
07/24/2024 12:33:10 - INFO - sentence_transformers.SentenceTransformer - Load pretrained SentenceTransformer: ./deps/sentence-t5-large
07/24/2024 12:33:11 - INFO - sentence_transformers.SentenceTransformer - Use pytorch device: cuda
07/24/2024 12:33:11 - INFO - mld.models.modeltype.mld - VAE Encoder: 7.634M
07/24/2024 12:33:11 - INFO - mld.models.modeltype.mld - VAE Decoder: 10.007M
07/24/2024 12:33:11 - INFO - mld.models.modeltype.mld - Denoiser: 8.221M
07/24/2024 12:33:12 - INFO - __main__ - ***** Running training *****
07/24/2024 12:33:12 - INFO - root -   Num examples = 24546
07/24/2024 12:33:12 - INFO - root -   Num Epochs = 1000
07/24/2024 12:33:12 - INFO - root -   Instantaneous batch size per device = 256
07/24/2024 12:33:12 - INFO - root -   Total optimization steps = 96000
1it [00:00, 439.10it/s]                                                                                                                                                             | 0/96000 [00:00<?, ?it/s]
1it [00:00, 555.10it/s]                                                                                                                                                               | 0/146 [00:00<?, ?it/s]
1it [00:00, 564.43it/s]                                                                                                                                                       | 1/146 [00:01<03:14,  1.34s/it]
1it [00:00, 567.80it/s]
1it [00:00, 575.51it/s]                                                                                                                                                       | 3/146 [00:01<00:57,  2.51it/s]
1it [00:00, 576.77it/s]
1it [00:00, 580.93it/s]                                                                                                                                                       | 5/146 [00:01<00:32,  4.32it/s]
1it [00:00, 560.51it/s]
1it [00:00, 577.41it/s]                                                                                                                                                       | 7/146 [00:01<00:22,  6.16it/s]
1it [00:00, 526.53it/s]
1it [00:00, 567.03it/s]                                                                                                                                                       | 9/146 [00:01<00:17,  8.03it/s]
1it [00:00, 561.49it/s]
1it [00:00, 577.25it/s]                                                                                                                                                      | 11/146 [00:02<00:14,  9.60it/s]
1it [00:00, 576.38it/s]
1it [00:00, 571.20it/s]                                                                                                                                                      | 13/146 [00:02<00:12, 11.05it/s]
1it [00:00, 572.29it/s]
1it [00:00, 579.24it/s]                                                                                                                                                      | 15/146 [00:02<00:10, 12.08it/s]
1it [00:00, 583.92it/s]
1it [00:00, 582.46it/s]█▌                                                                                                                                                    | 17/146 [00:02<00:09, 13.69it/s]
1it [00:00, 588.01it/s]
1it [00:00, 552.32it/s]███▊                                                                                                                                                  | 19/146 [00:02<00:09, 13.93it/s]
1it [00:00, 565.57it/s]
1it [00:00, 558.35it/s]██████▏                                                                                                                                               | 21/146 [00:02<00:08, 14.78it/s]
1it [00:00, 549.57it/s]
1it [00:00, 489.30it/s]████████▍                                                                                                                                             | 23/146 [00:02<00:08, 15.07it/s]
1it [00:00, 553.63it/s]
1it [00:00, 582.38it/s]██████████▊                                                                                                                                           | 25/146 [00:02<00:09, 13.23it/s]
1it [00:00, 573.15it/s]
1it [00:00, 561.94it/s]█████████████                                                                                                                                         | 27/146 [00:03<00:08, 13.84it/s]
 20%|█████████████████████████████████▎                                                                                                                                      | 29/146 [00:03<00:13,  8.96it/s]
Traceback (most recent call last):████▎                                                                                                                                      | 29/146 [00:03<00:08, 13.68it/s]
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sergej/projects/MotionLCM/train_motionlcm.py", line 440, in <module>
    main()
  File "/home/sergej/projects/MotionLCM/train_motionlcm.py", line 262, in main
    max_rp1, min_fid = validation()
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sergej/projects/MotionLCM/train_motionlcm.py", line 247, in validation
    for val_batch in tqdm(val_dataloader):
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sergej/miniforge3/envs/motionlcm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sergej/projects/MotionLCM/mld/data/humanml/dataset.py", line 279, in __getitem__
    raise ValueError("nan in motion")
ValueError: nan in motion

Steps:   0%|                                                                                                                                                                        | 0/96000 [00:03<?, ?it/s]
```

I see that there are some nans in the motion. Is this supposed to happen? If so, how do I proceed?

Note: I had the same issue as in #12 , namely my test.txt was also just 5 lines. In order to fix that, I copy pasted the test.txt from original humanml3d and that's how I got to this point.

**Comment by Dai-Wenxun** [comment]
hi, I updated the preparation guidance in https://github.com/Dai-Wenxun/MotionLCM/issues/6#issue-2274559944

You need to download the `txt`s from the provided google drive. the `txt`s in the official github is not complete.

![image](https://github.com/user-attachments/assets/9d1aaecc-6900-4127-b84d-528e66f90e2c)

**Comment by guson98** [comment]
Thank you, it is running now. :)
